/*
   This file was generated automatically by Alchitry Labs version 1.2.0.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module conversionAnswerLed_1 (
    input [9:0] ledValue,
    output reg [3:0] out
  );
  
  
  
  always @* begin
    
    case (ledValue)
      10'h001: begin
        out = 1'h0;
      end
      10'h002: begin
        out = 1'h1;
      end
      10'h004: begin
        out = 2'h2;
      end
      10'h008: begin
        out = 2'h3;
      end
      10'h010: begin
        out = 3'h4;
      end
      10'h020: begin
        out = 3'h5;
      end
      10'h040: begin
        out = 3'h6;
      end
      10'h080: begin
        out = 3'h7;
      end
      10'h100: begin
        out = 4'h8;
      end
      10'h200: begin
        out = 4'h9;
      end
      default: begin
        out = 1'h0;
      end
    endcase
  end
endmodule
