/*
   This file was generated automatically by Alchitry Labs version 1.2.0.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module led_move_11 (
    input clk,
    input rst,
    input [9:0] led_value,
    output reg out
  );
  
  
  
  wire [4-1:0] M_led_strip_pixel;
  wire [1-1:0] M_led_strip_led;
  reg [1-1:0] M_led_strip_update;
  reg [24-1:0] M_led_strip_color;
  ws2812b_writer_26 led_strip (
    .clk(clk),
    .rst(rst),
    .update(M_led_strip_update),
    .color(M_led_strip_color),
    .pixel(M_led_strip_pixel),
    .led(M_led_strip_led)
  );
  
  localparam LEDCOLOR0 = 240'h000000000000000000000000000000000000000000000000000000000000;
  
  localparam LEDCOLOR1 = 240'h000000000000000000000000000000000000000000000000000000ff0000;
  
  localparam LEDCOLOR2 = 240'h00000000000000000000000000000000000000000000000000ff00000000;
  
  localparam LEDCOLOR3 = 240'h0000000000000000000000000000000000000000000000ff000000000000;
  
  localparam LEDCOLOR4 = 240'h00000000000000000000000000000000000000ff00000000000000000000;
  
  localparam LEDCOLOR5 = 240'h000000000000000000000000000000ff0000000000000000000000000000;
  
  localparam LEDCOLOR6 = 240'h00000000000000000000000000ff00000000000000000000000000000000;
  
  localparam LEDCOLOR7 = 240'h0000000000000000000000ff000000000000000000000000000000000000;
  
  localparam LEDCOLOR8 = 240'h00000000000000ff00000000000000000000000000000000000000000000;
  
  localparam LEDCOLOR9 = 240'h000000ff0000000000000000000000000000000000000000000000000000;
  
  localparam LEDCOLOR10 = 240'h00ff00000000000000000000000000000000000000000000000000000000;
  
  always @* begin
    M_led_strip_color = 6'h00;
    if (led_value == 10'h000) begin
      M_led_strip_color = LEDCOLOR0[(M_led_strip_pixel)*24+23-:24];
    end else begin
      if (led_value == 10'h001) begin
        M_led_strip_color = LEDCOLOR1[(M_led_strip_pixel)*24+23-:24];
      end else begin
        if (led_value == 10'h002) begin
          M_led_strip_color = LEDCOLOR2[(M_led_strip_pixel)*24+23-:24];
        end else begin
          if (led_value == 10'h004) begin
            M_led_strip_color = LEDCOLOR3[(M_led_strip_pixel)*24+23-:24];
          end else begin
            if (led_value == 10'h008) begin
              M_led_strip_color = LEDCOLOR4[(M_led_strip_pixel)*24+23-:24];
            end else begin
              if (led_value == 10'h010) begin
                M_led_strip_color = LEDCOLOR5[(M_led_strip_pixel)*24+23-:24];
              end else begin
                if (led_value == 10'h020) begin
                  M_led_strip_color = LEDCOLOR6[(M_led_strip_pixel)*24+23-:24];
                end else begin
                  if (led_value == 10'h040) begin
                    M_led_strip_color = LEDCOLOR7[(M_led_strip_pixel)*24+23-:24];
                  end else begin
                    if (led_value == 10'h080) begin
                      M_led_strip_color = LEDCOLOR8[(M_led_strip_pixel)*24+23-:24];
                    end else begin
                      if (led_value == 10'h100) begin
                        M_led_strip_color = LEDCOLOR9[(M_led_strip_pixel)*24+23-:24];
                      end else begin
                        M_led_strip_color = LEDCOLOR10[(M_led_strip_pixel)*24+23-:24];
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
    M_led_strip_update = 1'h1;
    out = M_led_strip_led;
  end
endmodule
