/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_rngGen_rng_ready;
  wire [7-1:0] M_rngGen_out;
  rngGenerator_1 rngGen (
    .clk(clk),
    .rst(rst),
    .rng_ready(M_rngGen_rng_ready),
    .out(M_rngGen_out)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    usb_tx = usb_rx;
    io_led = 24'h000000;
    io_seg = 1'h0;
    io_sel = 1'h0;
    if (M_rngGen_rng_ready == 1'h1) begin
      io_led[0+7-:8] = M_rngGen_out;
    end
  end
endmodule
